### ISSUE TITLE
How to set a variable

### ISSUE THREAD

**Issue by scm2000** [zevv/zForth#15]
I've read through the code and the core functions.  I don't see how a user can define a new variable.   I see in other versions of forth you'd say something like:
VARIABLE varName

to define a new variable...

**Comment by zevv** [comment]
Variables can be declared with the `var` word that is defined in `core.zf` line 49. Use like this:

```forth
var counter  (create a variable named counter)
10 counter !  (store the number 10 in it)
1 counter +! (increas the counter by 1)
counter @ .  (read back and print)
```
