### ISSUE TITLE
Clarify the level of ANS Forth compliance

### ISSUE THREAD

**Issue by MaxBarraclough** [zevv/zForth#16]
I suggest the documentation should indicate how well zForth complies with the ANS Forth standard.

Related: if zForth has good compliance, I suggest submitting it to the big list of Forths: https://github.com/ForthHub/discussion/issues/19

**Comment by zevv** [comment]
Thanks, added to README.

I know almost nothing about what makes a Forth ANS compliant or compatible, and I'm not even sure I want to make the effort to find out :)
