### ISSUE TITLE
Missing some headers and C++ compatibility?

### ISSUE THREAD

**Issue by arabine** [zevv/zForth#29]
Hello !

While testing zforth, I had to add missing headers in zforth + C++ compatibility in zforth.h :

```C

// C++ compatibility header guard
#ifdef __cplusplus
extern "C"
{
#endif

#include <stddef.h> // for size_t
#include <stdarg.h> // for va_arg
#include <stdint.h> // for int32_t

...

#ifdef __cplusplus
}
#endif
```

**Comment by zevv** [comment]
Hmm, funny, I never needed that on any platform yet; what's your platform and compiler?

**Comment by zevv** [comment]
Ah right, that's pretty obvious, nevermind my previous remark. I'll fix this properly, because it's a bit of a mess now indeed.

**Comment by zevv** [comment]
Fixed in master, thanks!

**Comment by arabine** [comment]
Ok nice! Thanks.
