### ISSUE TITLE
I want to embed zForth into Tic-80

### ISSUE THREAD

**Issue by hunar1997** [zevv/zForth#34]
Hello :)

I like zForth, I haven't used it much yet, but it looks like the correct choise for embedding it into Tic-80 which is a Fantasy game console that supports many languages, I want to add forth to it. 

My initial choice was implementing my own forth but I'm afraid that I make bugs. so zForth it is.

The reason I posted this is because I don't know much about opensource contribution, so here a afew questions:

* Both repos are MIT so there are no problems, right?
* I need to change afew stuff like zfConf, so I will fork this repo. I'm allowed to modify right?
* Can I rename the language of my fork? for example call it ticForth? I don't want to right now but just asking.
* Do you have any advise for me?

Thanks :)

**Comment by zevv** [comment]
Hey there,

The license is totally permissive for everything you want to do with out:

- MIT should be fine for whatever you want, commercial or open source. 
- You can fork and modify all you want, no one can ever stop you from that
- You are free to rename the project as you please. It's considered good manners to credit the original author and project though.

As for advise: Forth is a funny language and not many people have the courage or patience to master it. There are other small and simple languages, be sure to consider the alternative before choosing zForth.

**Comment by hunar1997** [comment]
The renaming was just a question, I'll name it zforth :)

Well I wanted a small embedable forth and google showed zforth as first result, and the other ones on the list didnt look good enough.. if you know other ones I'll happily explore them :) 

One more thing. I couln't figure out what `@@ !! ,, .. ##` mean, can you explain it somewhere?

Thanks for the quick reply :D

**Comment by zevv** [comment]
> One more thing. I couln't figure out what `@@ !! ,, .. ##` mean, can
> you explain it somewhere?

These words are not for general use, they are primitives used to
implement `!`, `!`, `,` and `#`, see core.zf line 15. The implementation
of these words is in zforth.c, look for PRIM_PEEK, PRIM_POKE, PRIM_COMMA
and PRIM_COUNT.



-- 
:wq
^X^Cy^K^X^C^C^C^C
