### ISSUE TITLE
Floating Point segmentation fault 2017-07-23

### ISSUE THREAD

**Issue by rwhitworth** [zevv/zForth#4]
Hello, I was using American Fuzzy Lop (afl-fuzz) to fuzz input to the `zforth` program on Linux. Is fixing the crashes from these input files something you're interested in? The input files can be found here: https://github.com/rwhitworth/zForth-fuzz/tree/master/2017-07-23

The files can be executed as `./zforth id_filename` to cause seg faults.

Let me know if I can provide any more information to help narrow down this issue.

id:000000,sig:08,src:000098,op:flip4,pos:5

```
#0  0x0000000000405c84 in do_prim (op=<optimized out>, input=<optimized out>) at ../zforth/zforth.c:639
#1  run (input=<optimized out>) at ../zforth/zforth.c:465
#2  0x0000000000403404 in execute (addr=74) at ../zforth/zforth.c:497
#3  handle_word (buf=<optimized out>) at ../zforth/zforth.c:757
#4  handle_char (c=<optimized out>) at ../zforth/zforth.c:801
#5  zf_eval (buf=<optimized out>) at ../zforth/zforth.c:884
#6  0x00000000004017a6 in do_eval (src=<optimized out>, line=<optimized out>, buf=<optimized out>) at main.c:30
#7  include (fname=<optimized out>) at main.c:69
#8  0x0000000000402145 in main (argc=<optimized out>, argv=<optimized out>) at main.c:261
```

**Comment by zevv** [comment]
Thanks for testing and reporting, great job.

The floating point errors were trivial to fix, those were simply not handled in the div and mod primitives.

I'm trying to run zforth through afl myself to see if I can catch any other issues.

**Comment by zevv** [comment]
Afl complains that my test case is slow (60/sec), I'm running like so:

````
afl-fuzz -i input/ -o found src/linux/zforth @@
````

I'd expect hundreds or thousands of calls per second, any idea how to speed this ip?

**Comment by rwhitworth** [comment]
Thanks for the fast response.  I rebuilt master branch with afl-clang-fast (did you delete your comment?), re-tested, and the fix looks good.

**Comment by zevv** [comment]
Quoting Ryan Whitworth (2017-07-24 11:49:10)

> Thanks for the fast response.  I rebuilt master branch with
> afl-clang-fast (did you delete your comment?)

Yes, I did. The problem was caused by libreadline which seems to have a
bit of overhead. Compiling with noreadline=1 speeds up to 5K tests/sec
on my computer.

> re-tested, and the fix looks good.  

Thanks! again: great work!

--
:wq
^X^Cy^K^X^C^C^C^C
