### ISSUE TITLE
see for word definition

### ISSUE THREAD

**Issue by kmatze** [zevv/zForth#6]
Hi Ico,
in dict.zf you define the word **words** to view the words in Dictionary. thats good. but how to define a word **see** to view the code of a word?

thx and greetings - kmatze

**Comment by zevv** [comment]
Quoting kmatze (2018-11-03 20:25:19)

> in dict.zf you define the word **words** to view the words in
> Dictionary. thats good. but how to define a word **see** to view the
> code of a word?

Well, you'd need some forth code to do that, which I never got to
implement. Basically, you need to find the address of a word, skip the
length and name, and then decompile the word definition. I just made an
attempt to look into this, but I found the Forth language has completely
left my skull and I am no longer able to write any. I'm afraid you're on
your own here :)


--
:wq
^X^Cy^K^X^C^C^C^C
