### ISSUE TITLE
GPL

### ISSUE THREAD

**Issue by andrewtholt** [zevv/zForth#9]
Hi,

I am looking at zForth with a view to embedding into a product for use as to debug and test.

Since the product is an embedded system, and the whole thing is statically linked all of my code would then be covered by GPL (as I understand it) would it be possible to License zForth under more 'permissive' terms, such as LGPL or BSD ?

Regards,
Andrew

**Comment by zevv** [comment]
Changed to MIT, have fun!

**Comment by andrewtholt** [comment]
Hi,

Thanks.

Regards,
Andrew
